exports.up = async function (knex) {
  await knex.raw(`CREATE SCHEMA IF NOT EXISTS ema;`);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS ema.project_home_config (
      id_home_config integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      id_proyecto integer NOT NULL,
      id_plantilla integer NULL,

      kpi_primary_field_id integer NULL,
      kpi_secondary_field_ids jsonb NOT NULL DEFAULT '[]'::jsonb,

      preferred_date_field_id text NULL,
      preferred_time_grouping varchar(16) NULL,

      is_active boolean NOT NULL DEFAULT true,

      created_at timestamp without time zone NOT NULL DEFAULT now(),
      updated_at timestamp without time zone NOT NULL DEFAULT now(),
      created_by integer NULL,
      updated_by integer NULL,

      CONSTRAINT project_home_config_pkey PRIMARY KEY (id_home_config)
    );
  `);

  // Lookup support (project + plantilla + active)
  await knex.raw(`
    CREATE INDEX IF NOT EXISTS idx_project_home_config_lookup
    ON ema.project_home_config (id_proyecto, id_plantilla, is_active);
  `);

  // Prevent multiple active configs per (id_proyecto, id_plantilla), treating NULL as a real key.
  await knex.raw(`
    CREATE UNIQUE INDEX IF NOT EXISTS uq_project_home_config_active_combo
    ON ema.project_home_config (id_proyecto, COALESCE(id_plantilla, -1))
    WHERE is_active = true;
  `);
};

exports.down = async function (knex) {
  await knex.raw(`DROP TABLE IF EXISTS ema.project_home_config;`);
};

