exports.up = async function (knex) {
  await knex.raw(`CREATE SCHEMA IF NOT EXISTS ema;`);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS ema.project_home_item (
      id_home_item integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      id_proyecto integer NOT NULL,

      item_type varchar(32) NOT NULL,
      label text NULL,
      id_plantilla integer NULL,

      kpi_primary_field_id integer NULL,
      kpi_secondary_field_ids jsonb NOT NULL DEFAULT '[]'::jsonb,

      preferred_date_field_id text NULL,
      preferred_time_grouping varchar(16) NULL,

      sort_order integer NOT NULL DEFAULT 0,
      is_active boolean NOT NULL DEFAULT true,
      is_default boolean NOT NULL DEFAULT false,

      created_at timestamp without time zone NOT NULL DEFAULT now(),
      updated_at timestamp without time zone NOT NULL DEFAULT now(),

      CONSTRAINT project_home_item_pkey PRIMARY KEY (id_home_item),
      CONSTRAINT project_home_item_tipo_check CHECK (item_type IN ('informes')),
      CONSTRAINT project_home_item_proyecto_fk FOREIGN KEY (id_proyecto)
        REFERENCES ema.proyectos(gid)
    );
  `);

  await knex.raw(`
    CREATE INDEX IF NOT EXISTS idx_project_home_item_project_lookup
    ON ema.project_home_item (id_proyecto, item_type, is_active, sort_order, id_home_item);
  `);

  await knex.raw(`
    CREATE UNIQUE INDEX IF NOT EXISTS uq_project_home_item_default
    ON ema.project_home_item (id_proyecto, item_type)
    WHERE is_active = true AND is_default = true;
  `);
};

exports.down = async function (knex) {
  await knex.raw(`DROP TABLE IF EXISTS ema.project_home_item;`);
};

