// migrations/20260330123000_create_expediente_historial_visitas.js

exports.up = async function (knex) {
  await knex.raw(`CREATE SCHEMA IF NOT EXISTS ema;`);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS ema.expediente_historial_visitas (
      id_historial_visita integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      id_expediente integer NOT NULL,
      fecha date NULL,
      consultor text NULL,
      motivo text NULL,
      respuesta text NULL,
      documentos_recibidos jsonb NOT NULL DEFAULT '[]'::jsonb,
      created_at timestamp without time zone DEFAULT now(),
      CONSTRAINT expediente_historial_visitas_pkey PRIMARY KEY (id_historial_visita),
      CONSTRAINT expediente_historial_visitas_id_expediente_fkey
        FOREIGN KEY (id_expediente)
        REFERENCES ema.expedientes (id_expediente)
        ON UPDATE NO ACTION
        ON DELETE CASCADE
    );
  `);

  await knex.raw(`
    CREATE INDEX IF NOT EXISTS idx_expediente_historial_visitas_exp
    ON ema.expediente_historial_visitas (id_expediente);
  `);
};

exports.down = async function (knex) {
  await knex.raw(`DROP TABLE IF EXISTS ema.expediente_historial_visitas CASCADE;`);
};
