exports.up = async function (knex) {
  // Schema y extensión PostGIS
  await knex.raw(`CREATE SCHEMA IF NOT EXISTS ema;`);
  await knex.raw(`CREATE EXTENSION IF NOT EXISTS postgis;`);

  // =========================
  // ema.expedientes
  // =========================
  await knex.raw(`
    CREATE TABLE IF NOT EXISTS ema.expedientes (
      id_expediente integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      id_proyecto integer NOT NULL,
      fecha_relevamiento date,
      gps text,
      tecnico text,
      codigo_exp text,
      propietario_nombre text,
      propietario_ci text,
      tramo text,
      subtramo text,
      created_at timestamp without time zone DEFAULT now(),
      updated_at timestamp without time zone DEFAULT now(),
      carpeta_mejora jsonb NOT NULL DEFAULT '{}'::jsonb,
      carpeta_terreno jsonb NOT NULL DEFAULT '{}'::jsonb,
      carpeta_dbi jsonb NOT NULL DEFAULT '{}'::jsonb,
      CONSTRAINT expedientes_pkey PRIMARY KEY (id_expediente),
      CONSTRAINT expedientes_unique UNIQUE (id_proyecto, codigo_exp)
    );
  `);

  await knex.raw(`
    CREATE INDEX IF NOT EXISTS idx_expedientes_id_proyecto
    ON ema.expedientes (id_proyecto);
  `);

  // FK opcional hacia proyectos
  // Descomentá solo si querés asegurar relación física
  await knex.raw(`
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'expedientes_id_proyecto_fkey'
      ) THEN
        ALTER TABLE ema.expedientes
        ADD CONSTRAINT expedientes_id_proyecto_fkey
        FOREIGN KEY (id_proyecto)
        REFERENCES ema.proyectos (gid)
        ON UPDATE NO ACTION
        ON DELETE CASCADE;
      END IF;
    END$$;
  `);

  // =========================
  // ema.expediente_archivos
  // =========================
  await knex.raw(`
    CREATE TABLE IF NOT EXISTS ema.expediente_archivos (
      id_archivo integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      id_expediente integer NOT NULL,
      categoria text NOT NULL,
      filename text NOT NULL,
      originalname text,
      mimetype text,
      size_bytes bigint,
      path_rel text NOT NULL,
      created_at timestamp without time zone DEFAULT now(),
      CONSTRAINT expediente_archivos_pkey PRIMARY KEY (id_archivo)
    );
  `);

  await knex.raw(`
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'expediente_archivos_id_expediente_fkey'
      ) THEN
        ALTER TABLE ema.expediente_archivos
        ADD CONSTRAINT expediente_archivos_id_expediente_fkey
        FOREIGN KEY (id_expediente)
        REFERENCES ema.expedientes (id_expediente)
        ON UPDATE NO ACTION
        ON DELETE CASCADE;
      END IF;
    END$$;
  `);

  await knex.raw(`
    CREATE INDEX IF NOT EXISTS idx_exp_arch_categoria
    ON ema.expediente_archivos (categoria);
  `);

  await knex.raw(`
    CREATE INDEX IF NOT EXISTS idx_exp_arch_id_expediente
    ON ema.expediente_archivos (id_expediente);
  `);

  // =========================
  // ema.bloque_mejoras
  // =========================
  await knex.raw(`
    CREATE TABLE IF NOT EXISTS ema.bloque_mejoras (
      id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      id_proyecto integer NOT NULL,
      id_expediente integer,
      name text,
      descripcion text,
      geom geometry(MultiPolygon, 32721) NOT NULL,
      created_at timestamp without time zone DEFAULT now(),
      CONSTRAINT bloque_mejoras_pkey PRIMARY KEY (id)
    );
  `);

  await knex.raw(`
    CREATE INDEX IF NOT EXISTS idx_bloque_mejoras_exp
    ON ema.bloque_mejoras (id_expediente);
  `);

  await knex.raw(`
    CREATE INDEX IF NOT EXISTS idx_bloque_mejoras_proy
    ON ema.bloque_mejoras (id_proyecto);
  `);

  await knex.raw(`
    CREATE INDEX IF NOT EXISTS sidx_bloque_mejoras_geom
    ON ema.bloque_mejoras
    USING GIST (geom);
  `);

  await knex.raw(`
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'bloque_mejoras_id_expediente_fkey'
      ) THEN
        ALTER TABLE ema.bloque_mejoras
        ADD CONSTRAINT bloque_mejoras_id_expediente_fkey
        FOREIGN KEY (id_expediente)
        REFERENCES ema.expedientes (id_expediente)
        ON UPDATE NO ACTION
        ON DELETE SET NULL;
      END IF;
    END$$;
  `);

  await knex.raw(`
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'bloque_mejoras_id_proyecto_fkey'
      ) THEN
        ALTER TABLE ema.bloque_mejoras
        ADD CONSTRAINT bloque_mejoras_id_proyecto_fkey
        FOREIGN KEY (id_proyecto)
        REFERENCES ema.proyectos (gid)
        ON UPDATE NO ACTION
        ON DELETE CASCADE;
      END IF;
    END$$;
  `);

  // =========================
  // ema.bloque_terreno
  // =========================
  await knex.raw(`
    CREATE TABLE IF NOT EXISTS ema.bloque_terreno (
      id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      id_proyecto integer NOT NULL,
      id_expediente integer,
      name text,
      descripcion text,
      geom geometry(MultiPolygon, 32721) NOT NULL,
      created_at timestamp without time zone DEFAULT now(),
      CONSTRAINT bloque_terreno_pkey PRIMARY KEY (id)
    );
  `);

  await knex.raw(`
    CREATE INDEX IF NOT EXISTS idx_bloque_terreno_exp
    ON ema.bloque_terreno (id_expediente);
  `);

  await knex.raw(`
    CREATE INDEX IF NOT EXISTS idx_bloque_terreno_proy
    ON ema.bloque_terreno (id_proyecto);
  `);

  await knex.raw(`
    CREATE INDEX IF NOT EXISTS sidx_bloque_terreno_geom
    ON ema.bloque_terreno
    USING GIST (geom);
  `);

  await knex.raw(`
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'bloque_terreno_id_expediente_fkey'
      ) THEN
        ALTER TABLE ema.bloque_terreno
        ADD CONSTRAINT bloque_terreno_id_expediente_fkey
        FOREIGN KEY (id_expediente)
        REFERENCES ema.expedientes (id_expediente)
        ON UPDATE NO ACTION
        ON DELETE SET NULL;
      END IF;
    END$$;
  `);

  await knex.raw(`
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'bloque_terreno_id_proyecto_fkey'
      ) THEN
        ALTER TABLE ema.bloque_terreno
        ADD CONSTRAINT bloque_terreno_id_proyecto_fkey
        FOREIGN KEY (id_proyecto)
        REFERENCES ema.proyectos (gid)
        ON UPDATE NO ACTION
        ON DELETE CASCADE;
      END IF;
    END$$;
  `);
};

exports.down = async function (knex) {
  await knex.raw(`
    ALTER TABLE IF EXISTS ema.bloque_terreno
    DROP CONSTRAINT IF EXISTS bloque_terreno_id_expediente_fkey;
  `);

  await knex.raw(`
    ALTER TABLE IF EXISTS ema.bloque_terreno
    DROP CONSTRAINT IF EXISTS bloque_terreno_id_proyecto_fkey;
  `);

  await knex.raw(`
    ALTER TABLE IF EXISTS ema.bloque_mejoras
    DROP CONSTRAINT IF EXISTS bloque_mejoras_id_expediente_fkey;
  `);

  await knex.raw(`
    ALTER TABLE IF EXISTS ema.bloque_mejoras
    DROP CONSTRAINT IF EXISTS bloque_mejoras_id_proyecto_fkey;
  `);

  await knex.raw(`
    ALTER TABLE IF EXISTS ema.expediente_archivos
    DROP CONSTRAINT IF EXISTS expediente_archivos_id_expediente_fkey;
  `);

  await knex.raw(`
    ALTER TABLE IF EXISTS ema.expedientes
    DROP CONSTRAINT IF EXISTS expedientes_id_proyecto_fkey;
  `);

  await knex.raw(`DROP TABLE IF EXISTS ema.bloque_terreno CASCADE;`);
  await knex.raw(`DROP TABLE IF EXISTS ema.bloque_mejoras CASCADE;`);
  await knex.raw(`DROP TABLE IF EXISTS ema.expediente_archivos CASCADE;`);
  await knex.raw(`DROP TABLE IF EXISTS ema.expedientes CASCADE;`);
};