exports.up = async function (knex) {
  await knex.raw(`CREATE SCHEMA IF NOT EXISTS ema;`);
  await knex.raw(`CREATE EXTENSION IF NOT EXISTS postgis;`);

  // =========================================================
  // 1) ema.expedientes
  // =========================================================
  await knex.raw(`
    CREATE TABLE IF NOT EXISTS ema.expedientes (
      id_expediente integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    );
  `);

  await knex.raw(`
    ALTER TABLE ema.expedientes
      ADD COLUMN IF NOT EXISTS id_proyecto integer,
      ADD COLUMN IF NOT EXISTS fecha_relevamiento date,
      ADD COLUMN IF NOT EXISTS gps text,
      ADD COLUMN IF NOT EXISTS tecnico text,
      ADD COLUMN IF NOT EXISTS codigo_exp text,
      ADD COLUMN IF NOT EXISTS propietario_nombre text,
      ADD COLUMN IF NOT EXISTS propietario_ci text,
      ADD COLUMN IF NOT EXISTS tramo text,
      ADD COLUMN IF NOT EXISTS subtramo text,
      ADD COLUMN IF NOT EXISTS created_at timestamp without time zone DEFAULT now(),
      ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone DEFAULT now(),
      ADD COLUMN IF NOT EXISTS carpeta_mejora jsonb NOT NULL DEFAULT '{}'::jsonb,
      ADD COLUMN IF NOT EXISTS carpeta_terreno jsonb NOT NULL DEFAULT '{}'::jsonb,
      ADD COLUMN IF NOT EXISTS carpeta_dbi jsonb NOT NULL DEFAULT '{}'::jsonb;
  `);

  await knex.raw(`
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'ema'
          AND table_name = 'expedientes'
          AND column_name = 'id_proyecto'
      ) THEN
        UPDATE ema.expedientes
        SET id_proyecto = 0
        WHERE id_proyecto IS NULL;
      END IF;
    END$$;
  `);

  await knex.raw(`
    ALTER TABLE ema.expedientes
    ALTER COLUMN id_proyecto SET NOT NULL;
  `);

  await knex.raw(`
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'expedientes_unique'
      ) THEN
        ALTER TABLE ema.expedientes
        ADD CONSTRAINT expedientes_unique UNIQUE (id_proyecto, codigo_exp);
      END IF;
    END$$;
  `);

  await knex.raw(`
    CREATE INDEX IF NOT EXISTS idx_expedientes_id_proyecto
    ON ema.expedientes (id_proyecto);
  `);

  await knex.raw(`
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'ema'
          AND table_name = 'proyectos'
      )
      AND NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'expedientes_id_proyecto_fkey'
      ) THEN
        ALTER TABLE ema.expedientes
        ADD CONSTRAINT expedientes_id_proyecto_fkey
        FOREIGN KEY (id_proyecto)
        REFERENCES ema.proyectos (gid)
        ON UPDATE NO ACTION
        ON DELETE CASCADE;
      END IF;
    END$$;
  `);

  // =========================================================
  // 2) ema.expediente_archivos
  // =========================================================
  await knex.raw(`
    CREATE TABLE IF NOT EXISTS ema.expediente_archivos (
      id_archivo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    );
  `);

  await knex.raw(`
    ALTER TABLE ema.expediente_archivos
      ADD COLUMN IF NOT EXISTS id_expediente integer,
      ADD COLUMN IF NOT EXISTS categoria text,
      ADD COLUMN IF NOT EXISTS filename text,
      ADD COLUMN IF NOT EXISTS originalname text,
      ADD COLUMN IF NOT EXISTS mimetype text,
      ADD COLUMN IF NOT EXISTS size_bytes bigint,
      ADD COLUMN IF NOT EXISTS path_rel text,
      ADD COLUMN IF NOT EXISTS created_at timestamp without time zone DEFAULT now();
  `);

  await knex.raw(`
    CREATE INDEX IF NOT EXISTS idx_exp_arch_categoria
    ON ema.expediente_archivos (categoria);
  `);

  await knex.raw(`
    CREATE INDEX IF NOT EXISTS idx_exp_arch_id_expediente
    ON ema.expediente_archivos (id_expediente);
  `);

  await knex.raw(`
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'ema'
          AND table_name = 'expedientes'
      )
      AND NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'expediente_archivos_id_expediente_fkey'
      ) THEN
        ALTER TABLE ema.expediente_archivos
        ADD CONSTRAINT expediente_archivos_id_expediente_fkey
        FOREIGN KEY (id_expediente)
        REFERENCES ema.expedientes (id_expediente)
        ON UPDATE NO ACTION
        ON DELETE CASCADE;
      END IF;
    END$$;
  `);

  // Intentar dejar NOT NULL solo si no hay nulos
  await knex.raw(`
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'ema'
          AND table_name = 'expediente_archivos'
          AND column_name = 'id_expediente'
      ) AND NOT EXISTS (
        SELECT 1 FROM ema.expediente_archivos WHERE id_expediente IS NULL
      ) THEN
        ALTER TABLE ema.expediente_archivos
        ALTER COLUMN id_expediente SET NOT NULL;
      END IF;
    END$$;
  `);

  await knex.raw(`
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'ema'
          AND table_name = 'expediente_archivos'
          AND column_name = 'categoria'
      ) AND NOT EXISTS (
        SELECT 1 FROM ema.expediente_archivos WHERE categoria IS NULL
      ) THEN
        ALTER TABLE ema.expediente_archivos
        ALTER COLUMN categoria SET NOT NULL;
      END IF;
    END$$;
  `);

  await knex.raw(`
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'ema'
          AND table_name = 'expediente_archivos'
          AND column_name = 'filename'
      ) AND NOT EXISTS (
        SELECT 1 FROM ema.expediente_archivos WHERE filename IS NULL
      ) THEN
        ALTER TABLE ema.expediente_archivos
        ALTER COLUMN filename SET NOT NULL;
      END IF;
    END$$;
  `);

  await knex.raw(`
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'ema'
          AND table_name = 'expediente_archivos'
          AND column_name = 'path_rel'
      ) AND NOT EXISTS (
        SELECT 1 FROM ema.expediente_archivos WHERE path_rel IS NULL
      ) THEN
        ALTER TABLE ema.expediente_archivos
        ALTER COLUMN path_rel SET NOT NULL;
      END IF;
    END$$;
  `);

  // =========================================================
  // 3) ema.bloque_mejoras
  // =========================================================
  await knex.raw(`
    CREATE TABLE IF NOT EXISTS ema.bloque_mejoras (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    );
  `);

  await knex.raw(`
    ALTER TABLE ema.bloque_mejoras
      ADD COLUMN IF NOT EXISTS id_proyecto integer,
      ADD COLUMN IF NOT EXISTS id_expediente integer,
      ADD COLUMN IF NOT EXISTS name text,
      ADD COLUMN IF NOT EXISTS descripcion text,
      ADD COLUMN IF NOT EXISTS created_at timestamp without time zone DEFAULT now();
  `);

  // geom: se agrega aparte por PostGIS
  await knex.raw(`
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'ema'
          AND table_name = 'bloque_mejoras'
          AND column_name = 'geom'
      ) THEN
        ALTER TABLE ema.bloque_mejoras
        ADD COLUMN geom geometry(MultiPolygon,32721);
      END IF;
    END$$;
  `);

  await knex.raw(`
    CREATE INDEX IF NOT EXISTS idx_bloque_mejoras_exp
    ON ema.bloque_mejoras (id_expediente);
  `);

  await knex.raw(`
    CREATE INDEX IF NOT EXISTS idx_bloque_mejoras_proy
    ON ema.bloque_mejoras (id_proyecto);
  `);

  await knex.raw(`
    CREATE INDEX IF NOT EXISTS sidx_bloque_mejoras_geom
    ON ema.bloque_mejoras
    USING GIST (geom);
  `);

  await knex.raw(`
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'ema'
          AND table_name = 'expedientes'
      )
      AND NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'bloque_mejoras_id_expediente_fkey'
      ) THEN
        ALTER TABLE ema.bloque_mejoras
        ADD CONSTRAINT bloque_mejoras_id_expediente_fkey
        FOREIGN KEY (id_expediente)
        REFERENCES ema.expedientes (id_expediente)
        ON UPDATE NO ACTION
        ON DELETE SET NULL;
      END IF;
    END$$;
  `);

  await knex.raw(`
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'ema'
          AND table_name = 'proyectos'
      )
      AND NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'bloque_mejoras_id_proyecto_fkey'
      ) THEN
        ALTER TABLE ema.bloque_mejoras
        ADD CONSTRAINT bloque_mejoras_id_proyecto_fkey
        FOREIGN KEY (id_proyecto)
        REFERENCES ema.proyectos (gid)
        ON UPDATE NO ACTION
        ON DELETE CASCADE;
      END IF;
    END$$;
  `);

  // dejar NOT NULL en geom solo si no hay nulos
  await knex.raw(`
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'ema'
          AND table_name = 'bloque_mejoras'
          AND column_name = 'geom'
      ) AND NOT EXISTS (
        SELECT 1 FROM ema.bloque_mejoras WHERE geom IS NULL
      ) THEN
        ALTER TABLE ema.bloque_mejoras
        ALTER COLUMN geom SET NOT NULL;
      END IF;
    END$$;
  `);

  // =========================================================
  // 4) ema.bloque_terreno
  // =========================================================
  await knex.raw(`
    CREATE TABLE IF NOT EXISTS ema.bloque_terreno (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    );
  `);

  await knex.raw(`
    ALTER TABLE ema.bloque_terreno
      ADD COLUMN IF NOT EXISTS id_proyecto integer,
      ADD COLUMN IF NOT EXISTS id_expediente integer,
      ADD COLUMN IF NOT EXISTS name text,
      ADD COLUMN IF NOT EXISTS descripcion text,
      ADD COLUMN IF NOT EXISTS created_at timestamp without time zone DEFAULT now();
  `);

  await knex.raw(`
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'ema'
          AND table_name = 'bloque_terreno'
          AND column_name = 'geom'
      ) THEN
        ALTER TABLE ema.bloque_terreno
        ADD COLUMN geom geometry(MultiPolygon,32721);
      END IF;
    END$$;
  `);

  await knex.raw(`
    CREATE INDEX IF NOT EXISTS idx_bloque_terreno_exp
    ON ema.bloque_terreno (id_expediente);
  `);

  await knex.raw(`
    CREATE INDEX IF NOT EXISTS idx_bloque_terreno_proy
    ON ema.bloque_terreno (id_proyecto);
  `);

  await knex.raw(`
    CREATE INDEX IF NOT EXISTS sidx_bloque_terreno_geom
    ON ema.bloque_terreno
    USING GIST (geom);
  `);

  await knex.raw(`
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'ema'
          AND table_name = 'expedientes'
      )
      AND NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'bloque_terreno_id_expediente_fkey'
      ) THEN
        ALTER TABLE ema.bloque_terreno
        ADD CONSTRAINT bloque_terreno_id_expediente_fkey
        FOREIGN KEY (id_expediente)
        REFERENCES ema.expedientes (id_expediente)
        ON UPDATE NO ACTION
        ON DELETE SET NULL;
      END IF;
    END$$;
  `);

  await knex.raw(`
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'ema'
          AND table_name = 'proyectos'
      )
      AND NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'bloque_terreno_id_proyecto_fkey'
      ) THEN
        ALTER TABLE ema.bloque_terreno
        ADD CONSTRAINT bloque_terreno_id_proyecto_fkey
        FOREIGN KEY (id_proyecto)
        REFERENCES ema.proyectos (gid)
        ON UPDATE NO ACTION
        ON DELETE CASCADE;
      END IF;
    END$$;
  `);

  await knex.raw(`
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'ema'
          AND table_name = 'bloque_terreno'
          AND column_name = 'geom'
      ) AND NOT EXISTS (
        SELECT 1 FROM ema.bloque_terreno WHERE geom IS NULL
      ) THEN
        ALTER TABLE ema.bloque_terreno
        ALTER COLUMN geom SET NOT NULL;
      END IF;
    END$$;
  `);
};

exports.down = async function (knex) {
  // En una migración defensiva, el down conviene ser conservador.
  // Podés dejarlo vacío o solo quitar constraints/índices nuevos si querés.
};